version: "3.9"
services:
  postapp:
    build: .
    ports:
      - "3000:3000"
    links:
      - databasepostapp
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://databasepostapp/PostsApp
  databasepostapp:
    image: mongo
    ports:
      - "27017:27017"
    # logging:
    # driver: "none"
